Program initialized.
____________________________ 

Process ID = 85360

____________________________
Traceback (most recent call last):
  File "/users/jkoeller/Documents/Research/Pooley_Research/cluster/lensing_simulator/src/Main.py", line 70, in <module>
    run_simulation(args.run)
  File "/users/jkoeller/Documents/Research/Pooley_Research/cluster/lensing_simulator/src/Main.py", line 14, in run_simulation
    from app.calculator import ExperimentTableRunner
  File "/users/jkoeller/Documents/Research/Pooley_Research/cluster/lensing_simulator/src/app/calculator/__init__.py", line 4, in <module>
    from .ExperimentTableRunner import ExperimentTableRunner
  File "/users/jkoeller/Documents/Research/Pooley_Research/cluster/lensing_simulator/src/app/calculator/ExperimentTableRunner.py", line 6, in <module>
    from app.calculator.ExperimentResultCalculator import ExperimentResultCalculator, varyTrial
  File "/users/jkoeller/Documents/Research/Pooley_Research/cluster/lensing_simulator/src/app/calculator/ExperimentResultCalculator.py", line 8, in <module>
    import numpy as np
  File "/users/jkoeller/miniconda3/lib/python3.6/site-packages/numpy/__init__.py", line 158, in <module>
    from . import add_newdocs
  File "/users/jkoeller/miniconda3/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/users/jkoeller/miniconda3/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/users/jkoeller/miniconda3/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
ModuleNotFoundError: No module named 'numpy.core'
